import type { ComponentDefinition } from "@/types/lesson"

export const componentDefinitions: ComponentDefinition[] = [
  // Content Components
  {
    type: "paragraph",
    label: "Paragraph",
    category: "content",
    description: "A block of text with formatting options",
    icon: "¶",
    defaultProps: {
      content: "Enter your text here...",
      align: "left",
    },
    propDefinitions: [
      {
        name: "content",
        label: "Content",
        type: "richText",
        required: true,
        defaultValue: "Enter your text here...",
      },
      {
        name: "align",
        label: "Alignment",
        type: "select",
        required: false,
        defaultValue: "left",
        options: [
          { label: "Left", value: "left" },
          { label: "Center", value: "center" },
          { label: "Right", value: "right" },
          { label: "Justify", value: "justify" },
        ],
      },
    ],
  },
  {
    type: "heading",
    label: "Heading",
    category: "content",
    description: "A title or section header",
    icon: "H",
    defaultProps: {
      content: "Heading Text",
      level: 2,
      align: "left",
    },
    propDefinitions: [
      {
        name: "content",
        label: "Content",
        type: "string",
        required: true,
        defaultValue: "Heading Text",
      },
      {
        name: "level",
        label: "Heading Level",
        type: "select",
        required: true,
        defaultValue: 2,
        options: [
          { label: "H1 (Largest)", value: 1 },
          { label: "H2", value: 2 },
          { label: "H3", value: 3 },
          { label: "H4", value: 4 },
          { label: "H5", value: 5 },
          { label: "H6 (Smallest)", value: 6 },
        ],
      },
      {
        name: "align",
        label: "Alignment",
        type: "select",
        required: false,
        defaultValue: "left",
        options: [
          { label: "Left", value: "left" },
          { label: "Center", value: "center" },
          { label: "Right", value: "right" },
        ],
      },
    ],
  },
  {
    type: "bulletList",
    label: "Bullet List",
    category: "content",
    description: "Ordered or unordered list of items",
    icon: "•",
    defaultProps: {
      items: ["Item 1", "Item 2", "Item 3"],
      type: "unordered",
    },
    propDefinitions: [
      {
        name: "items",
        label: "List Items",
        type: "componentArray",
        required: true,
        defaultValue: ["Item 1", "Item 2", "Item 3"],
      },
      {
        name: "type",
        label: "List Type",
        type: "select",
        required: true,
        defaultValue: "unordered",
        options: [
          { label: "Unordered (Bullets)", value: "unordered" },
          { label: "Ordered (Numbers)", value: "ordered" },
        ],
      },
    ],
  },
  {
    type: "image",
    label: "Image",
    category: "content",
    description: "Display an image with optional caption",
    icon: "🖼️",
    defaultProps: {
      src: "/placeholder.svg?height=300&width=400",
      alt: "Image description",
      caption: "",
      width: "100%",
    },
    propDefinitions: [
      {
        name: "src",
        label: "Image Source",
        type: "image",
        required: true,
        defaultValue: "/placeholder.svg?height=300&width=400",
      },
      {
        name: "alt",
        label: "Alt Text",
        type: "string",
        required: true,
        defaultValue: "Image description",
      },
      {
        name: "caption",
        label: "Caption",
        type: "string",
        required: false,
        defaultValue: "",
      },
      {
        name: "width",
        label: "Width",
        type: "string",
        required: false,
        defaultValue: "100%",
      },
    ],
  },

  // Interactive Components
  {
    type: "quiz",
    label: "Quiz",
    category: "interactive",
    description: "Multiple choice quiz with automatic scoring",
    icon: "❓",
    defaultProps: {
      questions: [
        {
          id: "q1",
          question: "What is the capital of France?",
          options: [
            { id: "1", text: "London", isCorrect: false },
            { id: "2", text: "Paris", isCorrect: true },
            { id: "3", text: "Berlin", isCorrect: false },
            { id: "4", text: "Madrid", isCorrect: false },
          ],
          explanation: "Paris is the capital and most populous city of France.",
        },
      ],
      showExplanation: true,
      shuffleOptions: false,
      points: 10,
    },
    propDefinitions: [
      {
        name: "questions",
        label: "Questions",
        type: "componentArray",
        required: true,
        defaultValue: [
          {
            id: "q1",
            question: "What is the capital of France?",
            options: [
              { id: "1", text: "London", isCorrect: false },
              { id: "2", text: "Paris", isCorrect: true },
              { id: "3", text: "Berlin", isCorrect: false },
              { id: "4", text: "Madrid", isCorrect: false },
            ],
            explanation: "Paris is the capital and most populous city of France.",
          },
        ],
      },
      {
        name: "showExplanation",
        label: "Show Explanation",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "shuffleOptions",
        label: "Shuffle Options",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
      {
        name: "points",
        label: "Points Per Question",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
    ],
  },
  {
    type: "matchingPairs",
    label: "Matching Pairs",
    category: "interactive",
    description: "Match items from two columns",
    icon: "🔄",
    defaultProps: {
      title: "Match the items",
      pairs: [
        { id: "1", left: "Dog", right: "Bark" },
        { id: "2", left: "Cat", right: "Meow" },
        { id: "3", left: "Cow", right: "Moo" },
      ],
      shuffled: true,
      points: 15,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Match the items",
      },
      {
        name: "pairs",
        label: "Matching Pairs",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", left: "Dog", right: "Bark" },
          { id: "2", left: "Cat", right: "Meow" },
          { id: "3", left: "Cow", right: "Moo" },
        ],
      },
      {
        name: "shuffled",
        label: "Shuffle Items",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 0,
        max: 100,
      },
    ],
  },
  {
    type: "dragDrop",
    label: "Drag & Drop",
    category: "interactive",
    description: "Arrange items in the correct order",
    icon: "↕️",
    defaultProps: {
      title: "Arrange in the correct order",
      items: [
        { id: "1", text: "First item", correctIndex: 0 },
        { id: "2", text: "Second item", correctIndex: 1 },
        { id: "3", text: "Third item", correctIndex: 2 },
      ],
      shuffled: true,
      points: 15,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Arrange in the correct order",
      },
      {
        name: "items",
        label: "Items",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", text: "First item", correctIndex: 0 },
          { id: "2", text: "Second item", correctIndex: 1 },
          { id: "3", text: "Third item", correctIndex: 2 },
        ],
      },
      {
        name: "shuffled",
        label: "Shuffle Items",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 0,
        max: 100,
      },
    ],
  },
  {
    type: "flashcards",
    label: "Flashcards",
    category: "interactive",
    description: "Flip cards for memorization and revision",
    icon: "🔄",
    defaultProps: {
      title: "Flashcards",
      cards: [
        { id: "1", front: "What is the capital of France?", back: "Paris" },
        { id: "2", front: "What is the capital of Japan?", back: "Tokyo" },
        { id: "3", front: "What is the capital of Australia?", back: "Canberra" },
      ],
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Flashcards",
      },
      {
        name: "cards",
        label: "Flashcards",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", front: "What is the capital of France?", back: "Paris" },
          { id: "2", front: "What is the capital of Japan?", back: "Tokyo" },
          { id: "3", front: "What is the capital of Australia?", back: "Canberra" },
        ],
      },
    ],
  },
  {
    type: "hotspot",
    label: "Hotspot Image",
    category: "interactive",
    description: "Image with interactive, clickable regions",
    icon: "📍",
    defaultProps: {
      title: "Interactive Image",
      image: "/placeholder.svg?height=400&width=600",
      hotspots: [
        { id: "1", x: 0.3, y: 0.4, label: "Point 1", content: "This is the first point of interest" },
        { id: "2", x: 0.7, y: 0.6, label: "Point 2", content: "This is the second point of interest" },
      ],
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Interactive Image",
      },
      {
        name: "image",
        label: "Image",
        type: "image",
        required: true,
        defaultValue: "/placeholder.svg?height=400&width=600",
      },
      {
        name: "hotspots",
        label: "Hotspots",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", x: 0.3, y: 0.4, label: "Point 1", content: "This is the first point of interest" },
          { id: "2", x: 0.7, y: 0.6, label: "Point 2", content: "This is the second point of interest" },
        ],
      },
    ],
  },

  // Gamified Components
  {
    type: "scoreBoard",
    label: "Score Board",
    category: "gamified",
    description: "Display current score and progress",
    icon: "🏆",
    defaultProps: {
      title: "Your Score",
      showTotal: true,
      showPercentage: true,
      animation: true,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Your Score",
      },
      {
        name: "showTotal",
        label: "Show Total Score",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "showPercentage",
        label: "Show Percentage",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "animation",
        label: "Animate Score Changes",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
    ],
  },

  // Add more component definitions here...
]
